### ISSUE TITLE
Code not functional

### ISSUE THREAD

**Issue by qt1** [standupmaths/xmastree2020#18]
Some mathematicians purists could argue that the code in not functional!

There are many animations that can (and should) be expressed as a function of 4d space+time.
Thus colors of pixels are just a samples of this function at the LED coordinate t the time of the animation ```c_i = f(X_i)```.

**Comment by oliverdunk** [comment]
Hey @qt1! I agree that the lack of dimensions reflects poorly on someone with a book on the matter. It's a real crisis and something we need to resolve!

That said, Matt asked me to help with the maintenance of this repository, and I think as part of that I should probably close this one out. Sorry for being a grinch 😬

Your PR looks awesome! I'm figuring out how best to handle those and will comment on it soon.

**Comment by qt1** [comment]
Hi @oliverdunk , I just discovered Matt's video with the code running. Thanks for your contribution!

If you need anything now or in future, I'll be happy to help.
